// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StomatoloskaOrdinacija.Data;

namespace StomatoloskaOrdinacija.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200122184149_DodanKorisnikOsobljePacijentIStomatolog")]
    partial class DodanKorisnikOsobljePacijentIStomatolog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StomatoloskaOrdinacija.Data.EntityModels.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Mobitel")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");
                });

            modelBuilder.Entity("StomatoloskaOrdinacija.Data.EntityModels.MedicinskoOsoblje", b =>
                {
                    b.HasBaseType("StomatoloskaOrdinacija.Data.EntityModels.Korisnik");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.ToTable("MedicinskoOsoblje");

                    b.HasDiscriminator().HasValue("MedicinskoOsoblje");
                });

            modelBuilder.Entity("StomatoloskaOrdinacija.Data.EntityModels.Pacijent", b =>
                {
                    b.HasBaseType("StomatoloskaOrdinacija.Data.EntityModels.Korisnik");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.ToTable("Pacijenti");

                    b.HasDiscriminator().HasValue("Pacijent");
                });

            modelBuilder.Entity("StomatoloskaOrdinacija.Data.EntityModels.Stomatolog", b =>
                {
                    b.HasBaseType("StomatoloskaOrdinacija.Data.EntityModels.Korisnik");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnName("Stomatolog_DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titula")
                        .IsRequired()
                        .HasColumnName("Stomatolog_Titula")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.ToTable("Stomatolozi");

                    b.HasDiscriminator().HasValue("Stomatolog");
                });
#pragma warning restore 612, 618
        }
    }
}
